version: '3'

services:
  web:
    image: nginx
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env

  php:
    build: docker/php
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    env_file:
      - .env
