version: '3'

services:
  web:
    volumes:
      - mutagen_sync:/var/www/html:nocopy
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - "80:80"
      - "443:443"

  php:
    volumes:
      - ./:/var/www/html:cached
      - mutagen_sync:/mutagen_sync:nocopy
      - ./docker/php/xdebug.macos.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  mutagen_sync:
